package com.Doggo.DoggoEx.service.animals;

import com.Doggo.DoggoEx.dto.CatDto;
import com.Doggo.DoggoEx.dto.DogDto;
import org.springframework.stereotype.Service;

import java.util.HashMap;
import java.util.Map;

@Service
public class EngToKorService {

    public DogDto dogToKor(DogDto dogDto) {
        // DogDto에서 받고있는 영문 이름을 한국어로 변환
        // 첫번째 매개변수dogDto.getName에서  dogNameMapping 에서 정의한 이름과 똒~같으면  static하기 지정한 디폴트값 (한글명) 반환
        String koreanName = dogNameMapping.getOrDefault(dogDto.getName(), dogDto.getName());
        dogDto.setKoreanName(koreanName);
        return dogDto;
    }

    public CatDto catToKor(CatDto catDto) {
        // CatDto에서 받고있는 영문 이름을 한국어로 변환
        String koreanName = catNameMapping.getOrDefault(catDto.getName(), catDto.getName());
        catDto.setKoreanName(koreanName);
        return catDto;
    }
    // 수동으로 변환한 견종명들 , 고유명사라서 정확도 이슈로 직접함 , 건들면 으르렁
    private static final Map<String, String> dogNameMapping = new HashMap<>();

    static {
        dogNameMapping.put("American Bulldog", "아메리칸 불독");
        dogNameMapping.put("Australian Cattle Dog", "오스트레일리안 캐틀 독");
        dogNameMapping.put("Australian Kelpie", "오스트레일리안 켈피");
        dogNameMapping.put("Australian Stumpy Tail Cattle Dog", "오스트레일리안 스텀피 테일 캐틀 독");
        dogNameMapping.put("Azawakh", "아자와크");
        dogNameMapping.put("Basenji", "바센지");
        dogNameMapping.put("Bergamasco Sheepdog", "베르가마스코 쉽독");
        dogNameMapping.put("Briard", "브리아르");
        dogNameMapping.put("Broholmer", "브로홀머");
        dogNameMapping.put("Bullmastiff", "불마스티프");
        dogNameMapping.put("Catahoula Leopard Dog", "카타훌라 레오파드 독");
        dogNameMapping.put("Chow Chow", "차우 차우");
        dogNameMapping.put("Clumber Spaniel", "클럼버 스파니엘");
        dogNameMapping.put("Coton de Tulear", "코통 드 튈레아르");
        dogNameMapping.put("French Bulldog", "프렌치 불독");
        dogNameMapping.put("Golden Retriever", "골든 리트리버");
        dogNameMapping.put("Hovawart", "호바와트");
        dogNameMapping.put("Irish Water Spaniel", "아이리시 워터 스파니엘");
        dogNameMapping.put("Irish Wolfhound", "아이리시 울프하운드");
        dogNameMapping.put("Jagdterrier", "야그테리어");
        dogNameMapping.put("Kishu Ken", "키슈 견");
        dogNameMapping.put("Mastiff", "마스티프");
        dogNameMapping.put("Neapolitan Mastiff", "네오폴리탄 마스티프");
        dogNameMapping.put("Newfoundland", "뉴펀들랜드");
        dogNameMapping.put("Pekingese", "페키니즈");
        dogNameMapping.put("Pug", "퍼그");
        dogNameMapping.put("Pyrenean Mastiff", "피레니언 마스티프");
        dogNameMapping.put("Romanian Mioritic Shepherd Dog", "루마니안 미오리틱 셰퍼드 독");
        dogNameMapping.put("Rottweiler", "로트와일러");
        dogNameMapping.put("Saint Bernard", "세인트 버나드");
        dogNameMapping.put("Scottish Deerhound", "스코티시 디어하운드");
        dogNameMapping.put("Slovensky Cuvac", "슬로벤스키 쿠박");
        dogNameMapping.put("Small Munsterlander", "스몰 뮌스터랜더");
        dogNameMapping.put("Spanish Mastiff", "스페니시 마스티프");
        dogNameMapping.put("Whippet", "위펫");
        dogNameMapping.put("Akita", "아키타");
        dogNameMapping.put("Bavarian Mountain Scent Hound", "바바리안 마운틴 센트 하운드");
        dogNameMapping.put("Berger Picard", "베르제 피카르");
        dogNameMapping.put("Borzoi", "보르조이");
        dogNameMapping.put("Boston Terrier", "보스턴 테리어");
        dogNameMapping.put("Bracco Italiano", "브라코 이탈리아노");
        dogNameMapping.put("Braque du Bourbonnais", "브락 뒤 부르봉네");
        dogNameMapping.put("Bulldog", "불독");
        dogNameMapping.put("Caucasian Shepherd Dog", "코카시안 셰퍼드 독");
        dogNameMapping.put("Cirneco dell’Etna", "츠르네코 델 에트나");
        dogNameMapping.put("Dutch Shepherd", "더치 셰퍼드");
        dogNameMapping.put("English Toy Spaniel", "잉글리시 토이 스파니엘");
        dogNameMapping.put("Glen of Imaal Terrier", "글렌 오브 이말 테리어");
        dogNameMapping.put("Japanese Chin", "재패니즈 친");
        dogNameMapping.put("Lagotto Romagnolo", "라고토 로마뇰로");
        dogNameMapping.put("Nova Scotia Duck Tolling Retriever", "노바 스코샤 덕 톨링 리트리버");
        dogNameMapping.put("Porcelaine", "포르셀레인");
        dogNameMapping.put("Rafeiro do Alentejo", "라페이로 두 알렌테주");
        dogNameMapping.put("Rhodesian Ridgeback", "로디지언 리지백");
        dogNameMapping.put("Sloughi", "슬루기");
        dogNameMapping.put("Spinone Italiano", "스피노네 이탈리아노");
        dogNameMapping.put("Volpino Italiano", "볼피노 이탈리아노");
        dogNameMapping.put("Affenpinscher", "아펜핀셔");
        dogNameMapping.put("Afghan Hound", "아프간 하운드");
        dogNameMapping.put("Airedale Terrier", "에어데일 테리어");
        dogNameMapping.put("Alaskan Malamute", "알래스칸 말라뮤트");
        dogNameMapping.put("American Eskimo Dog", "아메리칸 에스키모 독");
        dogNameMapping.put("American Hairless Terrier", "아메리칸 헤어리스 테리어");
        dogNameMapping.put("American Leopard Hound", "아메리칸 레오파드 하운드");
        dogNameMapping.put("American Staffordshire Terrier", "아메리칸 스태퍼드셔 테리어");
        dogNameMapping.put("American Water Spaniel", "아메리칸 워터 스파니엘");
        dogNameMapping.put("Anatolian Shepherd Dog", "아나톨리안 셰퍼드 독");
        dogNameMapping.put("Australian Shepherd", "오스트레일리안 셰퍼드");
        dogNameMapping.put("Barbet", "바르벳");
        dogNameMapping.put("Beauceron", "보세롱");
        dogNameMapping.put("Bedlington Terrier", "베들링턴 테리어");
        dogNameMapping.put("Belgian Laekenois", "벨지안 레케노와");
        dogNameMapping.put("Belgian Malinois", "벨지안 말리노이");
        dogNameMapping.put("Belgian Sheepdog", "벨지안 쉽독");
        dogNameMapping.put("Belgian Tervuren", "벨지안 테뷰런");
        dogNameMapping.put("Bernese Mountain Dog", "버니즈 마운틴 독");
        dogNameMapping.put("Bichon Frise", "비숑 프리제");
        dogNameMapping.put("Biewer Terrier", "비워 테리어");
        dogNameMapping.put("Black Russian Terrier", "블랙 러시안 테리어");
        dogNameMapping.put("Boerboel", "보에르보엘");
        dogNameMapping.put("Bohemian Shepherd", "보헤미안 셰퍼드");
        dogNameMapping.put("Bolognese", "볼로네제");
        dogNameMapping.put("Border Terrier", "보더 테리어");
        dogNameMapping.put("Bouvier des Flandres", "부비에 데 플랑드르");
        dogNameMapping.put("Boxer", "복서");
        dogNameMapping.put("Boykin Spaniel", "보이킨 스파니엘");
        dogNameMapping.put("Braque Francais Pyrenean", "브락 프랑세 피레니안");
        dogNameMapping.put("Brittany", "브리타니");
        dogNameMapping.put("Bull Terrier", "불 테리어");
        dogNameMapping.put("Cane Corso", "케인 코르소");
        dogNameMapping.put("Carolina Dog", "카롤라이나 독");
        dogNameMapping.put("Cavalier King Charles Spaniel", "캐벌리어 킹 찰스 스파니엘");
        dogNameMapping.put("Central Asian Shepherd Dog", "센트럴 아시안 셰퍼드 독");
        dogNameMapping.put("Cesky Terrier", "체스키 테리어");
        dogNameMapping.put("Chesapeake Bay Retriever", "체서피크 베이 리트리버");
        dogNameMapping.put("Chinese Crested", "차이니스 크레스티드");
        dogNameMapping.put("Chinese Shar-Pei", "차이니스 샤페이");
        dogNameMapping.put("Cocker Spaniel", "코커 스패니얼");
        dogNameMapping.put("Croatian Sheepdog", "크로아티안 쉽독");
        dogNameMapping.put("Curly-Coated Retriever", "컬리 코티드 리트리버");
        dogNameMapping.put("Czechoslovakian Vlcak", "체코슬로바키안 블차크");
        dogNameMapping.put("Dalmatian", "달마시안");
        dogNameMapping.put("Dandie Dinmont Terrier", "댄디 딘몬트 테리어");
        dogNameMapping.put("Danish-Swedish Farmdog", "덴마크-스웨덴 팜독");
        dogNameMapping.put("Deutscher Wachtelhund", "도이쳐 바흐텔훈트");
        dogNameMapping.put("Doberman Pinscher", "도베르만 핀셔");
        dogNameMapping.put("Dogo Argentino", "도고 아르헨티노");
        dogNameMapping.put("Dogue de Bordeaux", "도그 드 보르도");
        dogNameMapping.put("Drentsche Patrijshond", "드렌테 파트리스혼드");
        dogNameMapping.put("English Cocker Spaniel", "잉글리시 코커 스패니얼");
        dogNameMapping.put("English Setter", "잉글리시 세터");
        dogNameMapping.put("English Springer Spaniel", "잉글리시 스프링어 스패니얼");
        dogNameMapping.put("Entlebucher Mountain Dog", "엔틀부허 마운틴 독");
        dogNameMapping.put("Estrela Mountain Dog", "에스트렐라 마운틴 독");
        dogNameMapping.put("Eurasier", "유라시어");
        dogNameMapping.put("Field Spaniel", "필드 스패니얼");
        dogNameMapping.put("Flat-Coated Retriever", "플랫 코티드 리트리버");
        dogNameMapping.put("French Spaniel", "프렌치 스패니얼");
        dogNameMapping.put("German Longhaired Pointer", "저먼 롱헤어드 포인터");
        dogNameMapping.put("German Pinscher", "저먼 핀셔");
        dogNameMapping.put("German Shepherd Dog", "저먼 셰퍼드 독");
        dogNameMapping.put("German Shorthaired Pointer", "저먼 쇼트헤어드 포인터");
        dogNameMapping.put("German Wirehaired Pointer", "저먼 와이어헤어드 포인터");
        dogNameMapping.put("Giant Schnauzer", "자이언트 슈나우저");
        dogNameMapping.put("Gordon Setter", "고든 세터");
        dogNameMapping.put("Great Dane", "그레이트 데인");
        dogNameMapping.put("Great Pyrenees", "그레이트 피레니즈");
        dogNameMapping.put("Greater Swiss Mountain Dog", "그레이터 스위스 마운틴 독");
        dogNameMapping.put("Greyhound", "그레이하운드");
        dogNameMapping.put("Hamiltonstovare", "해밀턴스토바레");
        dogNameMapping.put("Hokkaido", "홋카이도");
        dogNameMapping.put("Ibizan Hound", "이비잔 하운드");
        dogNameMapping.put("Irish Red and White Setter", "아이리시 레드 앤 화이트 세터");
        dogNameMapping.put("Irish Setter", "아이리시 세터");
        dogNameMapping.put("Irish Terrier", "아이리시 테리어");
        dogNameMapping.put("Italian Greyhound", "이탈리안 그레이하운드");
        dogNameMapping.put("Japanese Spitz", "재패니즈 스피츠");
        dogNameMapping.put("Jindo", "진돗개");
        dogNameMapping.put("Kai Ken", "카이 켄");
        dogNameMapping.put("Karelian Bear Dog", "카렐리안 베어 독");
        dogNameMapping.put("Komondor", "코몬도르");
        dogNameMapping.put("Kromfohrlander", "크롬포르란더");
        dogNameMapping.put("Kuvasz", "쿠바스");
        dogNameMapping.put("Labrador Retriever", "래브라도 리트리버");
        dogNameMapping.put("Lakeland Terrier", "레이크랜드 테리어");
        dogNameMapping.put("Leonberger", "레온베르거");
        dogNameMapping.put("Lhasa Apso", "라사 압소");
        dogNameMapping.put("Löwchen", "뢰벤");
        dogNameMapping.put("Maltese", "말티즈");
        dogNameMapping.put("Miniature American Shepherd", "미니어처 아메리칸 셰퍼드");
        dogNameMapping.put("Mountain Cur", "마운틴 커");
        dogNameMapping.put("Nederlandse Kooikerhondje", "네덜란드 코이커혼제");
        dogNameMapping.put("Norrbottenspets", "노르보텐스펫츠");
        dogNameMapping.put("Norwegian Lundehund", "노르웨이안 룬데훈드");
        dogNameMapping.put("Old English Sheepdog", "올드 잉글리시 쉽독");
        dogNameMapping.put("Parson Russell Terrier", "파슨 러셀 테리어");
        dogNameMapping.put("Perro de Presa Canario", "페로 데 프레사 카나리오");
        dogNameMapping.put("Peruvian Inca Orchid", "페루비안 인카 오키드");
        dogNameMapping.put("Pharaoh Hound", "파라오 하운드");
        dogNameMapping.put("Pointer", "포인터");
        dogNameMapping.put("Portuguese Podengo", "포르투갈 포덴고");
        dogNameMapping.put("Portuguese Podengo Pequeno", "포르투갈 포덴고 페케뇨");
        dogNameMapping.put("Portuguese Pointer", "포르투갈 포인터");
        dogNameMapping.put("Portuguese Sheepdog", "포르투갈 쉽독");
        dogNameMapping.put("Portuguese Water Dog", "포르투갈 워터 독");
        dogNameMapping.put("Pudelpointer", "푸델포인터");
        dogNameMapping.put("Puli", "풀리");
        dogNameMapping.put("Pumi", "푸미");
        dogNameMapping.put("Rat Terrier", "랫 테리어");
        dogNameMapping.put("Saluki", "살루키");
        dogNameMapping.put("Schapendoes", "샤펜도스");
        dogNameMapping.put("Shiba Inu", "시바 이누");
        dogNameMapping.put("Shih Tzu", "시츄");
        dogNameMapping.put("Shikoku", "시코쿠");
        dogNameMapping.put("Skye Terrier", "스카이 테리어");
        dogNameMapping.put("Slovakian Wirehaired Pointer", "슬로바키안 와이어헤어드 포인터");
        dogNameMapping.put("Slovensky Kopov", "슬로벤스키 코포브");
        dogNameMapping.put("Soft Coated Wheaten Terrier", "소프트 코티드 휘튼 테리어");
        dogNameMapping.put("Spanish Water Dog", "스페니시 워터 독");
        dogNameMapping.put("Stabyhoun", "스타비하운");
        dogNameMapping.put("Staffordshire Bull Terrier", "스태퍼드셔 불 테리어");
        dogNameMapping.put("Standard Schnauzer", "스탠다드 슈나우저");
        dogNameMapping.put("Sussex Spaniel", "서식스 스패니얼");
        dogNameMapping.put("Swedish Vallhund", "스웨덴 발훈드");
        dogNameMapping.put("Taiwan Dog", "타이완 독");
        dogNameMapping.put("Thai Ridgeback", "타이 리지백");
        dogNameMapping.put("Tibetan Mastiff", "티베탄 마스티프");
        dogNameMapping.put("Tibetan Spaniel", "티베탄 스패니얼");
        dogNameMapping.put("Tibetan Terrier", "티베탄 테리어");
        dogNameMapping.put("Tornjak", "토르냑");
        dogNameMapping.put("Tosa", "토사");
        dogNameMapping.put("Vizsla", "비즐라");
        dogNameMapping.put("Weimaraner", "와이머라너");
        dogNameMapping.put("Welsh Springer Spaniel", "웰시 스프링어 스패니얼");
        dogNameMapping.put("Wirehaired Pointing Griffon", "와이어헤어드 포인팅 그리폰");
        dogNameMapping.put("Wirehaired Vizsla", "와이어헤어드 비즐라");
        dogNameMapping.put("Working Kelpie", "워킹 켈피");
        dogNameMapping.put("Xoloitzcuintli", "쏠로이츠쿠인틀리");
        dogNameMapping.put("American English Coonhound", "아메리칸 잉글리시 쿤하운드");
        dogNameMapping.put("Appenzeller Sennenhund", "아펜젤러 젠넨훈드");
        dogNameMapping.put("Basset Fauve de Bretagne", "바셋 포브 드 브르타뉴");
        dogNameMapping.put("Basset Hound", "바셋 하운드");
        dogNameMapping.put("Beagle", "비글");
        dogNameMapping.put("Black and Tan Coonhound", "블랙 앤 탠 쿤하운드");
        dogNameMapping.put("Bluetick Coonhound", "블루틱 쿤하운드");
        dogNameMapping.put("Border Collie", "보더 콜리");
        dogNameMapping.put("Brussels Griffon", "브뤼셀 그리폰");
        dogNameMapping.put("Cairn Terrier", "케언 테리어");
        dogNameMapping.put("Drever", "드레버");
        dogNameMapping.put("Grand Basset Griffon Vendéen", "그랑 바셋 그리폰 방데언");
        dogNameMapping.put("Hanoverian Scenthound", "하노버리안 센트하운드");
        dogNameMapping.put("Havanese", "하바니즈");
        dogNameMapping.put("Icelandic Sheepdog", "아이슬란딕 쉽독");
        dogNameMapping.put("Keeshond", "키스혼드");
        dogNameMapping.put("Kerry Blue Terrier", "케리 블루 테리어");
        dogNameMapping.put("Lancashire Heeler", "랭커셔 힐러");
        dogNameMapping.put("Lapponian Herder", "라포니안 허더");
        dogNameMapping.put("Manchester Terrier (Standard)", "맨체스터 테리어 (스탠다드)");
        dogNameMapping.put("Manchester Terrier (Toy)", "맨체스터 테리어 (토이)");
        dogNameMapping.put("Mudi", "무디");
        dogNameMapping.put("Norfolk Terrier", "노퍽 테리어");
        dogNameMapping.put("Norwegian Buhund", "노르웨이안 부훈드");
        dogNameMapping.put("Norwegian Elkhound", "노르웨이안 엘크하운드");
        dogNameMapping.put("Norwich Terrier", "노위치 테리어");
        dogNameMapping.put("Pembroke Welsh Corgi", "펨브룩 웰시 코기");
        dogNameMapping.put("Polish Lowland Sheepdog", "폴리시 로우랜드 쉽독");
        dogNameMapping.put("Pomeranian", "포메라니안");
        dogNameMapping.put("Poodle (Miniature)", "푸들 (미니어처)");
        dogNameMapping.put("Poodle (Standard)", "푸들 (스탠다드)");
        dogNameMapping.put("Poodle (Toy)", "푸들 (토이)");
        dogNameMapping.put("Pyrenean Shepherd", "피레니언 셰퍼드");
        dogNameMapping.put("Redbone Coonhound", "레드본 쿤하운드");
        dogNameMapping.put("Russell Terrier", "러셀 테리어");
        dogNameMapping.put("Russian Toy", "러시안 토이");
        dogNameMapping.put("Russian Tsvetnaya Bolonka", "러시안 츠베트나야 볼론카");
        dogNameMapping.put("Schipperke", "스키퍼키");
        dogNameMapping.put("Scottish Terrier", "스코티시 테리어");
        dogNameMapping.put("Sealyham Terrier", "실리햄 테리어");
        dogNameMapping.put("Segugio Italiano", "세구지오 이탈리아노");
        dogNameMapping.put("Silky Terrier", "실키 테리어");
        dogNameMapping.put("Swedish Lapphund", "스웨디시 랩훈드");
        dogNameMapping.put("Teddy Roosevelt Terrier", "테디 루스벨트 테리어");
        dogNameMapping.put("Transylvanian Hound", "트랜실베이니안 하운드");
        dogNameMapping.put("Treeing Walker Coonhound", "트리잉 워커 쿤하운드");
        dogNameMapping.put("Welsh Terrier", "웰시 테리어");
        dogNameMapping.put("Wire Fox Terrier", "와이어 폭스 테리어");
        dogNameMapping.put("Yakutian Laika", "야쿠티안 라이카");
        dogNameMapping.put("Yorkshire Terrier", "요크셔 테리어");
        dogNameMapping.put("American Foxhound", "아메리칸 폭스하운드");
        dogNameMapping.put("Australian Terrier", "오스트레일리안 테리어");
        dogNameMapping.put("Barbado da Terceira", "바르바도 다 테르세이라");
        dogNameMapping.put("Bearded Collie", "비어디드 콜리");
        dogNameMapping.put("Bloodhound", "블러드하운드");
        dogNameMapping.put("Canaan Dog", "카난 독");
        dogNameMapping.put("Cardigan Welsh Corgi", "카디건 웰시 코기");
        dogNameMapping.put("Chihuahua", "치와와");
        dogNameMapping.put("Chinook", "치누크");
        dogNameMapping.put("Collie", "콜리");
        dogNameMapping.put("Dachshund", "닥스훈트");
        dogNameMapping.put("English Foxhound", "잉글리시 폭스하운드");
        dogNameMapping.put("Finnish Lapphund", "핀니시 랩훈드");
        dogNameMapping.put("Finnish Spitz", "핀니시 스피츠");
        dogNameMapping.put("German Spitz", "저먼 스피츠");
        dogNameMapping.put("Harrier", "해리어");
        dogNameMapping.put("Miniature Bull Terrier", "미니어처 불 테리어");
        dogNameMapping.put("Miniature Pinscher", "미니어처 핀셔");
        dogNameMapping.put("Miniature Schnauzer", "미니어처 슈나우저");
        dogNameMapping.put("Otterhound", "오타하운드");
        dogNameMapping.put("Papillon", "파피용");
        dogNameMapping.put("Petit Basset Griffon Vendéen", "페티 바셋 그리폰 벤데옌");
        dogNameMapping.put("Samoyed", "사모예드");
        dogNameMapping.put("Shetland Sheepdog", "셰틀랜드 쉽독");
        dogNameMapping.put("Siberian Husky", "시베리안 허스키");
        dogNameMapping.put("Smooth Fox Terrier", "스무스 폭스 테리어");
        dogNameMapping.put("Treeing Tennessee Brindle", "트리잉 테네시 브린들");
        dogNameMapping.put("West Highland White Terrier", "웨스트 하이랜드 화이트 테리어");

    }


    private static final Map<String, String> catNameMapping = new HashMap<>();
    static {
        catNameMapping.put("Himalayan", "히말라얀");
        catNameMapping.put("Ragdoll Cats", "래그돌");
        catNameMapping.put("Aphrodite Giant", "아프로디테 자이언트");
        catNameMapping.put("Bambino", "밤비노");
        catNameMapping.put("Birman", "버만");
        catNameMapping.put("British Longhair", "브리티시 롱헤어");
        catNameMapping.put("Chantilly-Tiffany", "샹틸리-티파니");
        catNameMapping.put("Chartreux", "샤트록스");
        catNameMapping.put("Cymric", "심릭");
        catNameMapping.put("Donskoy", "돈스코이");
        catNameMapping.put("Exotic", "엑조틱");
        catNameMapping.put("German Rex", "저먼 렉스");
        catNameMapping.put("Lykoi", "라이코이");
        catNameMapping.put("Napoleon", "나폴레옹");
        catNameMapping.put("Nebelung", "네벨룽");
        catNameMapping.put("Norwegian Forest", "노르웨이안 포레스트");
        catNameMapping.put("Persian", "페르시안");
        catNameMapping.put("Peterbald", "피터볼드");
        catNameMapping.put("Pixie-Bob", "픽시 밥");
        catNameMapping.put("Russian Blue", "러시안 블루");
        catNameMapping.put("Scottish Fold", "스코티시 폴드");
        catNameMapping.put("Selkirk Rex", "셀커크 렉스");
        catNameMapping.put("Siberian", "시베리안");
        catNameMapping.put("Sphynx", "스핑크스");
        catNameMapping.put("Ukrainian Levkoy", "우크라이니안 레브코이");
        catNameMapping.put("York Chocolate", "요크 초콜릿");
        catNameMapping.put("Abyssinian", "아비시니안");
        catNameMapping.put("American Bobtail", "아메리칸 밥테일");
        catNameMapping.put("Asian", "아시안");
        catNameMapping.put("Foldex", "폴덱스");
        catNameMapping.put("Highlander", "하이랜더");
        catNameMapping.put("Manx", "맹크스");
        catNameMapping.put("Somali", "소말리");
        catNameMapping.put("Aegean", "에게안");
        catNameMapping.put("American Curl", "아메리칸 컬");
        catNameMapping.put("American Shorthair", "아메리칸 쇼트헤어");
        catNameMapping.put("Australian Mist", "오스트레일리안 미스트");
        catNameMapping.put("Balinese", "발리니즈");
        catNameMapping.put("Bengal Cats", "벵골 고양이");
        catNameMapping.put("Bombay", "봄베이");
        catNameMapping.put("Brazilian Shorthair", "브라질리안 쇼트헤어");
        catNameMapping.put("British Shorthair", "브리티시 쇼트헤어");
        catNameMapping.put("Burmilla", "버밀라");
        catNameMapping.put("Chinese Li Hua", "차이니즈 리 후아");
        catNameMapping.put("Colorpoint Shorthair", "컬러포인트 쇼트헤어");
        catNameMapping.put("Cyprus", "키프러스");
        catNameMapping.put("Desert Lynx", "데저트 린스");
        catNameMapping.put("Egyptian Mau", "이집션 마우");
        catNameMapping.put("Japanese Bobtail", "재패니즈 밥테일");
        catNameMapping.put("Javanese", "자바니즈");
        catNameMapping.put("Khao Manee", "카오 마니");
        catNameMapping.put("LaPerm", "라펌");
        catNameMapping.put("Maine Coon", "메인쿤");
        catNameMapping.put("Ocicat", "오시캣");
        catNameMapping.put("Oriental Bicolor", "오리엔탈 바이컬러");
        catNameMapping.put("Ragamuffin", "래거머핀");
        catNameMapping.put("Savannah", "사바나");
        catNameMapping.put("Serengeti", "세렝게티");
        catNameMapping.put("Siamese Cat", "샴 고양이");
        catNameMapping.put("Singapura", "싱가푸라");
        catNameMapping.put("Sokoke", "소코케");
        catNameMapping.put("Tonkinese", "통키니즈");
        catNameMapping.put("Toyger", "토이거");
        catNameMapping.put("Turkish Angora", "터키시 앙고라");
        catNameMapping.put("Turkish Van", "터키시 밴");
        catNameMapping.put("American Wirehair", "아메리칸 와이어헤어");
        catNameMapping.put("Arabian Mau", "아라비안 마우");
        catNameMapping.put("Burmese", "버마즈");
        catNameMapping.put("California Spangled", "캘리포니아 스팽글드");
        catNameMapping.put("Chausie", "챠우시");
        catNameMapping.put("Cornish Rex", "코니쉬 렉스");
        catNameMapping.put("Devon Rex", "데본 렉스");
        catNameMapping.put("European Burmese", "유러피안 버마즈");
        catNameMapping.put("European Shorthair", "유러피안 쇼트헤어");
        catNameMapping.put("Havana Brown", "하바나 브라운");
        catNameMapping.put("Korat", "코랏");
        catNameMapping.put("Kurilian Bobtail", "쿠릴리안 밥테일");
        catNameMapping.put("Mekong Bobtail", "메콩 밥테일");
        catNameMapping.put("Snowshoe", "스노슈");
        catNameMapping.put("Thai", "타이");
        catNameMapping.put("Thai Lilac", "타이 라일락");


    }
}
